package.json
src/components/team/TeamList.vue
src/components/team/TeamRegister.vue
src/components/team/TeamUpdate.vue
src/views/AppLogin.vue
src/views/PostView.vue
src/views/SignUp.vue
vue.config.js

서버 포트 수정 및 관련 axios url 수정
- port : 3011
- axios url 모두 http://localhost:8087 로 요청

[송현준] 서버 포트 수정 및 관련 axios url 수정

---

src/stores/auth.js

[송현준] 새로고침 pinia userinfo 초기화 문제 수정

[송현준] 새로고침 pinia userinfo 초기화 문제 수정

---

.env.development
package-lock.json
package.json
src/components/common/Header.vue
src/components/common/SearchBar.vue
src/router/index.js
src/stores/auth.js
src/views/post/PostDetail.vue
src/views/post/PostList.vue
src/views/post/PostWrite.vue
src/views/post/comment/CommentCreate.vue
src/views/post/comment/CommentItem.vue
src/views/post/comment/CommentList.vue

댓글 crud, 
게시글 북마크 기능,
댓글 좋아요 기능,
페이지네이션 기능

[임현조] 댓글 crud, 게시글 북마크, 댓글 좋아요, 페이지네이션 기능

---

src/router/index.js
src/views/admin/UserAllPost.vue
src/views/admin/UserDetail.vue

[홍도현] 관리자 페이지 로직 수정

---

src/router/index.js
src/stores/auth.js
src/views/feedback/FeedbackCreate.vue
src/views/feedback/ProjectFeedbackList.vue
src/views/feedback/UserFeedbackList.vue

- auth.js user 추가
- 피드백
user가 작성한 피드백 조회
user가 참여한 프로젝트의 모든 프로젝트 조회
피드백 CRUD

[홍도현] 피드백 로직 추가

---

src/components/common/Header.vue
src/components/forms/MessageForm.vue
src/components/forms/ProjectForm.vue
src/components/forms/TeamForm.vue
src/components/tables/MessageTable.vue
src/components/tables/TeamTable.vue
src/views/message/AddMessage.vue
src/views/message/Messages.vue
src/views/project/AddProject.vue
src/views/team/TeamDetail.vue
src/views/team/Teams.vue

[송현준] 팀 및 프로젝트 코드 임시 등록

---

src/components/forms/UserForm.vue
src/stores/user.js
src/views/user/UserDetail.vue

[송현준] 마이페이지 완료

---

src/components/common/PageNav.vue
src/components/project/ProjectInfo.vue
src/components/project/ProjectTechList.vue
src/views/post/PostList.vue
src/views/project/ProjectDetail.vue
src/views/project/ProjectList.vue
src/views/project/ProjectWrite.vue
src/views/team/TeamDeteil.vue
src/views/team/TeamList.vue
src/views/team/TeamWrite.vue

- 팀 CRUD 수정
- 프로젝트 CRUD 수정
- 페이징 버튼 롤백 및 디자인 변경

[홍재민] CRUD 수정 및 디자인 변경

---

src/components/common/Header.vue
src/components/tables/MessageTable.vue
src/views/message/AddMessage.vue
src/views/message/Messages.vue
src/views/post/AddPost.vue
src/views/post/PostDetail.vue
src/views/post/PostList.vue
src/views/post/comment/CommentItem.vue
src/views/project/ProjectDetail.vue

[임현조] 뷰 css 수정

---

src/components/project/ProjectInfo.vue
src/views/post/PostDetail.vue
src/views/project/ProjectDetail.vue
src/views/team/TeamDeteil.vue
src/views/team/TeamList.vue

- [홍재민] 팀 정렬, 스케줄, 프로젝트 게시판 수정

[홍재민] 팀 정렬, 스케줄, 프로젝트 게시판 수정

---

src/components/common/UpdatePasswordForm.vue
src/layout/AdminLayout.vue
src/router/index.js
src/stores/auth.js
src/views/admin/AdminLogin.vue
src/views/auth/UpdatePassword.vue
src/views/post/PostDetail.vue

admin 로그인 및 PostDetail 경로 관련 수정

[송현준] admin 로그인 및 PostDetail 경로 관련 수정

---

src/router/index.js

[송현준] 관리자 페이지 router 수정

---

src/views/post/PostDetail.vue
src/views/team/TeamList.vue

PostDetail, TeamList conflict 해결

[송현준] PostDetail, TeamList conflict 해결

---

src/views/common/NotificationBox.vue
src/views/message/AddMessage.vue
src/views/message/MessageDetail.vue
src/views/message/Messages.vue

[송현준] 알림 및 쪽지 전환 완료

---

src/views/message/Messages.vue

[송현준] 쪽지 보낸, 받은 사람 파라미터 수정

---

src/views/common/NotificationBox.vue

[송현준] 알림 username undefined 해결

---

src/components/project/ProjectInfo.vue
src/views/project/ProjectDetail.vue

[송현준] 프로젝트 수정

---

src/components/project/ProjectInfo.vue

[송현준] 프로젝트 인포 수정

---

src/views/schedule/ScheduleDeteil.vue
src/views/schedule/ScheduleWrite.vue

[송현준] 스케줄 폼 취소 버튼 생성

---

src/views/Home.vue

[송현준] 홈 화면 구성

---

src/views/Home.vue

[송현준] 홈 화면 라우터 링크 수정

---

src/components/common/Header.vue
src/views/message/MessageDetail.vue
src/views/message/Messages.vue
src/views/team/TeamDeteil.vue

[김민석]쪽지 디자인 수정

---

src/stores/auth.js
src/views/post/PostDetail.vue
src/views/post/comment/CommentCreate.vue
src/views/post/comment/CommentItem.vue
src/views/post/comment/CommentList.vue

[임현조] 댓글 생성 수정

---

src/components/common/SearchBar.vue
src/views/post/comment/CommentCreate.vue
src/views/post/comment/CommentItem.vue
src/views/post/comment/CommentList.vue

[임현조] 댓글 css 수정

---

src/router/index.js
src/stores/auth.js

[송현준] 관리자 로그인 수정

---

src/router/index.js
src/stores/user.js
src/views/Home.vue
src/views/user/UserMyCommentList.vue
src/views/user/UserMyPostList.vue
src/views/user/UserMyProjectList.vue

- Home css 수정
- 유저 상세페이지에서 유저별 댓글, 게시글, 프로젝트 조회

[홍도현] 유저 상세페이지에서 유저별 조회

---

src/components/common/UpdatePasswordForm.vue
src/components/forms/SignUpForm.vue
src/stores/auth.js

[송현준] 비밀번호 변경시 유저 이메일 체크

---

src/components/forms/SignUpForm.vue

[송현준] 회원가입 인증 수정

---

src/views/post/PostDetail.vue

[송현준] 게시글 수정, 삭제 버튼 조건 처리

---

src/stores/auth.js

[송현준] 로그인 에러 처리 수정

---

src/router/index.js
src/views/admin/AdminLogin.vue

[송현준] 관리자 로그인 로직 에러 수정

---

src/views/project/ProjectList.vue
src/views/team/TeamList.vue

게시글, 프로젝트 리스트 태그 스타일 변경
- closed 일때 빨간색으로 변경

[홍도현] 게시글, 프로젝트 리스트 태그 스타일 변경

---

src/views/report/Reports.vue

[송현준] 신고 수정

---

src/views/report/ReportDetail.vue

[송현준] 신고 수정시 신고 목록으로 보내기

---

src/views/report/ReportDetail.vue

[송현준] 신고 처리 후 관리자 페이지로 보내기

---

src/router/index.js

[송현준] 관리자 로그인 로직 변경

---

src/components/forms/UserForm.vue

[송현준] 마이페이지 수정 못하게 readonly 처리

---

src/components/forms/UserForm.vue

[송현준] 개인정보 수정 기능 생성
